### PR TITLE
*Optimize JS for hiding menu sections

### PR DESCRIPTION
**Pull request by MarcinFortuna**

### CODE REVIEW

**Comment by piotrbarcik** [comment]
Ok I agree.

**Comment by KajaSzarafinska** [comment]
wow Marcin well done :+1:

**Review by piotrbarcik — APPROVED** [review]
:+1:

**Review by KajaSzarafinska — APPROVED** [review]

**Review by norbertbrzeski — APPROVED** [review]
:+1:

**Comment by KajaSzarafinska** [comment]
:+1:

**Pull request merged**
